run:
  timeout: 5m
  allow-parallel-runners: true

issues:
  # don't skip warning about doc comments
  # don't exclude the default set of lint
  exclude-use-default: false
  # restore some of the defaults
  # (fill in the rest as needed)
  exclude-rules:
    - path: "api/*"
      linters:
        - lll
    - path: "internal/*"
      linters:
        - dupl
        - lll
    - path-except: "api/*"
      linters:
        - kal

linters:
  disable-all: true
  enable:
    - copyloopvar
    - dupl
    - errcheck
    - ginkgolinter
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - kal
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused

linters-settings:
  revive:
    rules:
      - name: comment-spacings
  custom:
    kal:
      type: "module"
      description: KAL is the Kube-API-Linter and lints Kube like APIs based on API conventions and best practices.
      settings:
        linters:
          enable:
          - "commentstart"
          - "conditions"
          - "integers"
          - "jsontags"
          # NOTE: maxlength check currently trips over our Status fields
          # missing a MaxLength marker
          # - "maxlength"
          # NOTE: we have a number of boolean fields. Should we convert them to
          # string?
          # - "nobools"
          - "nophase"
          - "optionalorrequired"
          - "requiredfields"
        lintersConfig:
          conditions:
            isFirstField: Warn
            useProtobuf: Ignore
