FROM registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.26-openshift-5.0 AS builder

WORKDIR /workspace
COPY . .
RUN CGO_ENABLED=0 GOOS=${GOOS} GOPROXY=${GOPROXY} go build \
  -ldflags "${LDFLAGS} -extldflags '-static'" \
  -o manager \
  cmd/manager/main.go

FROM registry.ci.openshift.org/ocp/5.0:base-rhel9

LABEL description="OpenStack Resource Controller Manager"
COPY --from=builder /workspace/manager .
COPY openshift/capi-operator-manifests /capi-operator-manifests

ENTRYPOINT ["/manager"]

LABEL io.openshift.release.operator=true
