apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: devstack-

components:
- ../../components/kustomizeconfig

resources:
- ../centos-stream
- provider-network.yaml
- flavor.yaml
- port.yaml
- securitygroup.yaml
- server.yaml

secretGenerator:
- name: userdata
  files:
  - value=user.data
  options:
    disableNameSuffixHash: true
