apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: true
  pairs:
    cluster.x-k8s.io/provider: infrastructure-openstack

namePrefix: orc-

resources:
- orc

components:
- ../components/namespaced
- ../components/common
- ../components/tech-preview

images:
- name: controller
  newName: registry.ci.openshift.org/openshift
  newTag: openstack-resource-controller
