apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Network
metadata:
  name: orc-imported-provider-network
spec:
  cloudCredentialsRef:
    cloudName: openstack
    secretName: cloud-config
  managementPolicy: unmanaged
  import:
    filter:
      name: provider_net_dualstack_1
