apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# This module imports the credentials secret so kustomize knows what it was
# renamed to and can update references to it accordingly, but patches it so
# that the secret itself will not be emitted.

resources:
- ../../credentials

patches:
- target:
    kind: Secret
    name: cloud-config
  patch: |-
    - op: add
      path: /metadata/annotations/config.kubernetes.io~1local-config
      value: "true"
