apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

transformers:
# Set namespace to openshift-cluster-api on all namespaced objects without an explicit namespace
- |-
  apiVersion: builtin
  kind: NamespaceTransformer
  metadata:
    name: _ignored_
    namespace: openshift-cluster-api
  setRoleBindingSubjects: none
  unsetOnly: true
  fieldSpecs:
  - path: metadata/name
    kind: Namespace
    create: true
