apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
- ../components/namespaced
- ../components/common
- ../components/tech-preview

generatorOptions:
  disableNameSuffixHash: true
  labels:
    provider.cluster.x-k8s.io/name: openstack
    provider.cluster.x-k8s.io/type: infrastructure
    provider.cluster.x-k8s.io/version: v0.8.0

configMapGenerator:
- name: openstack-resource-controller
  files:
  - components=infrastructure-components.yaml
