---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Network
metadata:
  name: provider-network
spec:
  cloudCredentialsRef:
    cloudName: openstack
    secretName: cloud-config
  managementPolicy: unmanaged
  import:
    filter:
      name: provider_net_dualstack_1
---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Subnet
metadata:
  name: provider-subnet-ipv4
spec:
  cloudCredentialsRef:
    cloudName: openstack
    secretName: cloud-config
  managementPolicy: unmanaged
  networkRef: provider-network
  import:
    filter:
      ipVersion: 4
---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Subnet
metadata:
  name: provider-subnet-ipv6
spec:
  cloudCredentialsRef:
    cloudName: openstack
    secretName: cloud-config
  managementPolicy: unmanaged
  networkRef: provider-network
  import:
    filter:
      ipVersion: 6
