---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Image
metadata:
  name: centos-stream-9
spec:
  cloudCredentialsRef:
    cloudName: openstack
    secretName: dev-test-cloud-config
  managementPolicy: managed
  managedOptions:
    onDelete: detach
  resource:
    name: CentOS-Stream-GenericCloud-9-20241209.0.x86_64
    content:
      diskFormat: qcow2
      download:
        url: https://cloud.centos.org/centos/9-stream/x86_64/images/CentOS-Stream-GenericCloud-9-20241209.0.x86_64.qcow2
        hash:
          algorithm: sha256
          value: 912218b89cdcd8e62b1207f19b62f4da756b793902d34116758b5ffb02859c5c
