apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
- tools/vendor/github.com/openshift/cluster-capi-operator/manifests-gen

resources:
- ../config/default

images:
- name: controller
  newName: registry.ci.openshift.org/openshift
  newTag: openstack-resource-controller
