on:
  push:
    branches:
    - release-1.0
  pull_request:
name: go test
permissions:
  contents: read

jobs:
  unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - '1'

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - run: |
         make test 
